#!/bin/sh

#HOME=$(eval echo ~$SUDO_USER)

# Install dependencies
sudo apt install i3 rxvt zsh python3-pip redshift thunar maim imagemagick ninja-build meson zathura feh neovim curl
sudo apt install libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre2-dev libpcre3-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev

# Set ZSH
chsh -s $(which zsh)

# Link config files
ln -f .Xdefaults .zshrc $HOME

mkdir -p $HOME/.config/i3
mkdir -p $HOME/.config/i3status
mkdir -p $HOME/.config/picom
mkdir -p $HOME/.config/VSCodium/User
mkdir -p $HOME/.config/nvim

ln -f .config/i3/* $HOME/.config/i3/
ln -f .config/i3status/* $HOME/.config/i3status/
ln -f .config/picom/* $HOME/.config/picom/
ln -f .config/VSCodium/User/* $HOME/.config/VSCodium/User/
ln -f .config/nvim/* $HOME/.config/nvim/

# Link scripts
sudo ln -f bin/* /usr/local/bin
sudo ln -f sbin/* /usr/local/sbin

# Add i3lockmore
if [ ! -e "/usr/local/bin/i3lockmore" ]; then
	sudo curl https://raw.githubusercontent.com/SammysHP/i3lockmore/master/i3lockmore -o /usr/local/bin/i3lockmore
	sudo chmod +x /usr/local/bin/i3lockmore
fi
if [ ! -e "/usr/local/bin/i3lockmore.png" ]; then
	sudo curl https://github.com/SammysHP/i3lockmore/raw/master/lock-icon.png -o /usr/local/bin/i3lockmore.png
fi

# Link /etc
sudo cp etc/sudoers.d/* /etc/sudoers.d/

# Install pywal
/usr/bin/python3 -m pip install pywal

# Install picom
if [ ! -d "picom" ]; then
    git clone https://github.com/yshui/picom.git
    cd picom
    git submodule update --init --recursive
    meson --buildtype=release . build
    ninja -C build
    sudo ninja -C build install
    cd ..
fi
