#!/bin/sh

#HOME=$(eval echo ~$SUDO_USER)

# Check for paru
if ! command -v paru &> /dev/null; then
    echo "Installing paru"
    sudo pacman -Sy --needed base-devel
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
    cd ..
    rm -rf paru
fi

# Install graphical dependencies
if [ "$1" != "--nogui" ]; then
    paru -Sy --noconfirm --needed rxvt-unicode redshift thunar maim zathura feh ttf-font-awesome i3lockmore-git python-pywal picom-git playerctl otf-sfmono-patched rofi vscodium-bin xorg-xinput noto-fonts-emoji pavucontrol blueman pango dunst ttf-dejavu backlight_control upower autorandr
else
    echo "Skipping GUI tools installation"
fi

# Install console dependencies
paru -Sy --noconfirm --needed git zsh python-pip neovim curl xcwd-git bat man-pages man-db cronie

# Set git settings
git config --global user.name "Thibault Nocchi"
git config --global user.email "1619359+ThibaultNocchi@users.noreply.github.com"

# Set ZSH
if [ "$SHELL" != "/usr/bin/zsh" ]; then
    chsh -s $(which zsh)
fi

# Link config files
ln -f .xinitrc .Xresources .zprofile .zshrc $HOME

mkdir -p $HOME/.config/i3
mkdir -p $HOME/.config/i3status
mkdir -p $HOME/.config/picom
mkdir -p $HOME/.config/VSCodium/User
mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/sheldon
mkdir -p $HOME/.config/pipewire/media-session.d
mkdir -p $HOME/.config/redshift

ln -f .config/i3/* $HOME/.config/i3/
ln -f .config/i3status/* $HOME/.config/i3status/
ln -f .config/picom/* $HOME/.config/picom/
ln -f .config/VSCodium/product.json $HOME/.config/VSCodium/product.json
ln -f .config/VSCodium/User/* $HOME/.config/VSCodium/User/
ln -f .config/nvim/* $HOME/.config/nvim/
ln -f .config/sheldon/* $HOME/.config/sheldon/
ln -f .config/pipewire/media-session.d/* $HOME/.config/pipewire/media-session.d
ln -f .config/redshift/* $HOME/.config/redshift/
sudo ln -f etc/modprobe.d/hid_apple.conf /etc/modprobe.d/hid_apple.conf

# Link scripts
sudo ln -f bin/* /usr/local/bin

# Enable redshift
systemctl --user --now enable redshift.service
