# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.paru-completion]
remote = 'https://raw.githubusercontent.com/Morganamilo/paru/master/completions/zsh'
apply = ["fpath"]

[plugins.gopass]
remote = 'https://raw.githubusercontent.com/gopasspw/gopass/master/zsh.completion'
apply = ["fpath"]

# ZSH completions before OMZ

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

# Bash completions after OMZ

[plugins.azcli]
remote = 'https://raw.githubusercontent.com/Azure/azure-cli/dev/az.completion'
apply = ["source"]
