# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
completion = { value = 'mkdir -p "$ZSH/completions"; ln -f -s "{{ file }}" "$ZSH/completions/_{{ name }}"', each = true }

[plugins]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.paru-completion]
remote = 'https://raw.githubusercontent.com/Morganamilo/paru/master/completions/zsh'
apply = ["fpath"]

[plugins.pass]
remote = 'https://git.zx2c4.com/password-store/plain/src/completion/pass.zsh-completion'
apply = ["completion"]


[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
