#!/bin/bash
MIN=375
MAX=$(</sys/class/backlight/intel_backlight/max_brightness)
CURRENT=$(</sys/class/backlight/intel_backlight/brightness)
PERCENT_STEP=$((MAX/100))
if [[ $# -eq 0 ]]; then
	PERCENT_CURRENT=$((CURRENT/PERCENT_STEP))
	echo $PERCENT_CURRENT
	exit
fi
DIFF=$((PERCENT_STEP*$1))
NEW=$((DIFF+CURRENT))
if [[ $NEW -gt $MAX ]]; then
	NEW=$MAX
elif [[ $NEW -lt $MIN ]]; then
	NEW=$MIN
fi
echo $NEW > /sys/class/backlight/intel_backlight/brightness
